[versions]
agp = "8.8.0"
kotlin = "2.0.21"
kspVersion = "2.0.21-1.0.27"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
composeBom = "2024.04.01"
appcompat = "1.7.0"
material = "1.12.0"
hiltVersion = "2.51.1"
navigationComposeHilt = "1.2.0"
navVersion = "2.8.6"
firebaseVersion = "33.8.0"
serialization = "1.7.3"
service = "4.4.2"
firebaseCrashlytics = "3.0.2"
okhttpVersion = "4.12.0"
retrofitVersion = "2.11.0"
roomVersion = "2.6.1"
dataStoreVersion = "1.1.2"
retrofit2KotlinxSerializationConverter = "1.0.0"
core-splashscreen = "1.0.1"
workManager = "2.10.0"
hiltWork = "1.2.0"

[libraries]
#core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-workmanager-corutines = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
#ui
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navVersion" }
#DI
hiltdagger = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hiltdaggerCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVersion" }
navigationComposeHilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "navigationComposeHilt" }
hiltwork = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
hiltworkCompiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltWork" }
#firebase
androidx-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseVersion" }
androidx-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
androidx-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
androidx-firebase-remoute-config = { group = "com.google.firebase", name = "firebase-config-ktx" }
#network
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttpVersion" }
retrofitConverter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
okhttpInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpVersion" }
#storage
room = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStoreVersion" }

#test
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[bundles]
kspBundles = [
    "roomCompiler",
    "hiltdaggerCompiler",
    "hiltworkCompiler"
]
hilt = [
    "hiltdagger",
    "navigationComposeHilt",
    "hiltwork"
]
firebase = [
    "androidx-firebase-analytics",
    "androidx-firebase-crashlytics",
    "androidx-firebase-remoute-config"
]
storage = [
    "dataStore",
    "room",
    "roomKtx"
]
network = [
    "retrofit",
    "retrofitConverter",
    "retrofit2-kotlinx-serialization-converter",
    "okhttp",
    "okhttpInterceptor"
]
ui = [
    "androidx-compose-bom",
    "androidx-ui",
    "androidx-ui-graphics",
    "androidx-ui-tooling",
    "androidx-ui-tooling-preview",
    "androidx-material3",
    "androidx-ui-navigation"
]
core = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",
    "androidx-activity-compose",
    "androidx-workmanager-corutines",
    "core-splashscreen"
]
test = [
    "androidx-ui-test-manifest",
    "androidx-ui-test-junit4",
    "junit",
    "androidx-junit",
    "androidx-espresso-core"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
android-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "service" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }

